(() => {
'use strict';
const T=THREE,U=THREE.MathUtils,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const chapters=[
{no:'00',en:'PROLOGUE',loc:'ARCHIVE ROOT',kicker:'ARCHIVE_ROOT',title:'悖论的灰烬',sub:'Ashes of Paradox',quote:'“这是一个关于 <em>#ERR_01</em> 的故事。”',body:'这个文明同时掌握了极致的效率与极致的浪漫，最终在自身的矛盾中迎来冻结。',scene:'origin',action:''},
{no:'01',en:'JUDGEMENT',loc:'SECTOR 07 / CAPITAL',kicker:'PURE_WHITE_PROTOCOL',title:'纯白的审判',sub:'The White Judgement',quote:'“光并没有照亮城市。它只是删除了阴影。”',body:'审判降临前的最后一秒，整座城市仍在运行。六千四百万扇窗，像神经元一样同时发光。',scene:'megacity',action:'启动审判'},
{no:'02',en:'FROZEN LAND',loc:'CRYOGENIC BASIN',kicker:'ABSOLUTE_ZERO_FRONTIER',title:'冻结的钢铁阔叶林',sub:'The Frozen Jungle',quote:'“这里的风，仍记得机器最后一次呼吸。”',body:'高楼从冰原中生长，桥梁悬在凝固的云层之上。文明没有毁灭，它被封存在一个永不抵达的明天。',scene:'frozen',action:'潜入冰层'},
{no:'03',en:'ECHOES',loc:'MEMORY VAULT 19',kicker:'AMBER_MEMORY_ARRAY',title:'琥珀里的回声',sub:'Echoes in Amber',quote:'“我们留下的不是遗言，是尚未播放完的生活。”',body:'记忆被压缩成发光的几何体，在黑暗中缓慢自转。每一块碎片，都储存着一个人的黄昏。',scene:'echo',action:'解析记忆'},
{no:'04',en:'BABEL',loc:'CENTRAL LIBRARY',kicker:'ENCRYPTED_LAMENT',title:'加密的叹息',sub:'The Silent Babel',quote:'“当所有语言都被保存，沉默成为唯一的禁书。”',body:'无限书架沿着重力的反方向延伸。纸张早已腐朽，文字却在光束中继续迁徙。',scene:'library',action:'解密残卷'},
{no:'05',en:'SILVER ARROW',loc:'TRANSIT LINE Ω',kicker:'TEMPORAL_EXPRESS',title:'切断时间的银矢',sub:'The Silver Arrow',quote:'“列车没有终点。它只是比世界更快地逃离昨天。”',body:'车窗之外，城市被速度拉成漫长的光。时间开始倒退，废墟一层层恢复成尚未坍塌的形状。',scene:'train',action:'逆转时间'},
{no:'Ω',en:'EPILOGUE',loc:'NULL / AFTERMATH',kicker:'ASHES_AFTER_PARADOX',title:'然后，灰烬醒来',sub:'After the Paradox',quote:'“毁灭不是终点。被记住，才是文明最后的形态。”',body:'一切结构最终消散，只剩无数灰烬围绕微弱的光旋转。你所看到的，正是它重新开始讲述自己的方式。',scene:'ashes',action:'重新开始'}];
const $=s=>document.querySelector(s),els={boot:$('#boot'),enter:$('#enter'),exp:$('#experience'),copy:$('#copy'),no:$('#chapterNo'),en:$('#chapterEn'),loc:$('#location'),kicker:$('#kicker'),title:$('#title'),sub:$('#subtitle'),quote:$('#quote'),body:$('#body'),action:$('#action'),rail:$('#rail'),trans:$('#transition'),flash:$('#flash'),coord:$('#coord'),atmos:$('#atmos'),clock:$('#clock')};
const renderer=new T.WebGLRenderer({canvas:$('#world'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.88;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
const scene=new T.Scene();scene.background=new T.Color(0x030506);scene.fog=new T.FogExp2(0x030506,.018);const camera=new T.PerspectiveCamera(47,innerWidth/innerHeight,.1,500);camera.position.set(0,4,20);const clock=new T.Clock();
scene.add(new T.HemisphereLight(0xb4d7df,0x090607,.62));const moon=new T.DirectionalLight(0xd8f2ff,2.6);moon.position.set(-16,24,12);moon.castShadow=true;scene.add(moon);const warm=new T.PointLight(0xff9e54,40,70,2);warm.position.set(9,1,-8);scene.add(warm);
const root=new T.Group();scene.add(root);let current=0,targetCam=new T.Vector3(),targetLook=new T.Vector3(),look=new T.Vector3(),pointer=new T.Vector2(),started=false,busy=false,eventTime=-99;
function rand(seed){let v=seed>>>0;return()=>((v=(v*1664525+1013904223)>>>0)/4294967296)}
function mat(color,rough=.65,metal=.25){return new T.MeshStandardMaterial({color,roughness:rough,metalness:metal})}
function box(w,h,d,m,x,y,z,parent=root){const o=new T.Mesh(new T.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;parent.add(o);return o}
function particles(n,color,size,spread,parent=root){const g=new T.BufferGeometry(),p=new Float32Array(n*3),r=rand(n+size*100);for(let i=0;i<n;i++){p[i*3]=(r()-.5)*spread[0];p[i*3+1]=(r()-.5)*spread[1];p[i*3+2]=(r()-.5)*spread[2]}g.setAttribute('position',new T.BufferAttribute(p,3));const o=new T.Points(g,new T.PointsMaterial({color,size,transparent:true,opacity:.65,depthWrite:false,blending:T.AdditiveBlending}));parent.add(o);return o}
const worlds={};function group(name){const g=new T.Group();g.name=name;g.visible=false;root.add(g);worlds[name]=g;return g}
function buildOrigin(){const g=group('origin');const grid=new T.GridHelper(120,80,0x1f6c66,0x102e2c);grid.position.y=-4;g.add(grid);const core=new T.Mesh(new T.IcosahedronGeometry(2.4,3),new T.MeshPhysicalMaterial({color:0x65e9d5,emissive:0x0c5f58,emissiveIntensity:1.5,wireframe:true,transparent:true,opacity:.5}));core.position.set(7,1,-7);core.userData.spin=1;g.add(core);for(let i=0;i<11;i++){const ring=new T.Mesh(new T.TorusGeometry(3+i*.72,.012,4,120),new T.MeshBasicMaterial({color:0x4db9ad,transparent:true,opacity:.13}));ring.position.copy(core.position);ring.rotation.set(Math.PI/2,i*.11,i*.17);ring.userData.spin=(i%2?1:-1)*(.08+i*.005);g.add(ring)}const p=particles(900,0x6adccd,.045,[52,35,45],g);p.userData.flow='rain'}
function building(g,r,x,z,w,h,d,ice=false){const shell=box(w,h,d,mat(ice?0x203a48:[0x111821,0x17222e,0x222a35][Math.floor(r()*3)],ice?.18:.64,ice?.1:.38),x,-4+h/2,z,g);if(ice){shell.material.transparent=true;shell.material.opacity=.7}const rows=Math.floor(h/.45),cols=Math.max(1,Math.floor(w/.35));const winMat=new T.MeshBasicMaterial({color:r()>.42?0x79d8ed:0xffbf73});for(let yy=0;yy<rows;yy++)for(let xx=0;xx<cols;xx++){if(r()<.42)continue;const win=box(.11,.17,.025,winMat,x-w/2+(xx+.5)*w/cols,-4+.34+yy*.43,z+d/2+.014,g);win.castShadow=false}if(r()>.45){const top=box(w*.55,.35+r()*.8,d*.55,shell.material,x,-4+h+.25,z,g);top.castShadow=true}if(r()>.7){const ant=new T.Mesh(new T.CylinderGeometry(.015,.025,.9+r(),6),mat(0x8a969f,.3,.9));ant.position.set(x,-3.4+h,z);g.add(ant)}return shell}
function buildCity(name,frozen=false){const g=group(name),r=rand(frozen?247:77);const ground=box(110,.4,100,mat(frozen?0xb8d7e0:0x090d12,frozen?.24:.9,frozen?.04:.1),0,-4.4,-22,g);ground.receiveShadow=true;for(let lane=0;lane<5;lane++)for(let i=0;i<24;i++){const x=-37+i*3.3+r()*.8,z=-8-lane*9-r()*4;building(g,r,x,z,.8+r()*1.9,3+r()*(frozen?15:20),.8+r()*2.1,frozen)}for(const x of[-10,10]){const road=box(8,.05,90,mat(0x080b0e,.95,.05),x,-4.16,-22,g);for(let z=-58;z<20;z+=4)box(.12,.06,1.6,new T.MeshBasicMaterial({color:0xd8d09c}),x,-4.1,z,g)}const bridge=box(65,.35,1.4,mat(0x39434d,.46,.65),0,1,-17,g);for(let x=-28;x<30;x+=6)box(.45,5.2,.6,bridge.material,x,-1.7,-17,g);const dust=particles(frozen?2100:700,frozen?0xcff5ff:0x6ab8c4,frozen?.055:.035,[90,34,100],g);dust.userData.flow=frozen?'snow':'city';g.userData.city=true}
function buildEcho(){const g=group('echo');for(let i=0;i<19;i++){const geo=new T.IcosahedronGeometry(.5+Math.random()*1.7,1),m=new T.MeshPhysicalMaterial({color:i%3?0x0ca99a:0xe29a43,emissive:i%3?0x064c47:0x713b11,emissiveIntensity:2,transmission:.42,transparent:true,opacity:.55,roughness:.08});const o=new T.Mesh(geo,m);o.position.set((Math.random()-.5)*28,(Math.random()-.5)*15,-4-Math.random()*25);o.userData.float=Math.random()*6;o.userData.spin=.1+Math.random()*.25;g.add(o)}particles(750,0x2dd4bf,.04,[42,26,50],g)}
function buildLibrary(){const g=group('library'),r=rand(33),wood=mat(0x4b2916,.78,.04);for(let side of[-1,1])for(let level=0;level<8;level++){const y=-4+level*2.5;box(22,.2,3,wood,side*12,y,-14,g);for(let i=0;i<34;i++){const h=1.2+r()*.9,w=.18+r()*.34;box(w,h,1.5,mat(new T.Color().setHSL(r(),.45,.16+r()*.16),.8,.03),side*12-10+i*.6,y+h/2+.14,-13.8,g)}}for(let i=0;i<7;i++){const ray=new T.SpotLight(0xffd18b,80,60,.16,.9);ray.position.set(-20+i*7,19,-3);ray.target.position.set(-14+i*5,-5,-22);g.add(ray,ray.target)}particles(850,0xe0ae62,.035,[55,35,55],g).userData.flow='dust'}
function buildTrain(){const g=group('train'),r=rand(501);for(let layer=0;layer<4;layer++)for(let i=0;i<25;i++){const h=3+r()*12,w=1+r()*3,o=box(w,h,1+r()*2,mat(new T.Color().setHSL(.57,.1,.3+layer*.12),.5,.36),-48+i*4+r(),-4+h/2,-9-layer*8,g);o.userData.train=layer}for(const x of[-1.6,1.6])box(.16,.12,140,mat(0xb6c1cb,.22,.9),x,-3.9,-35,g);particles(1000,0xd9e6ee,.035,[90,28,80],g).userData.flow='streak'}
function buildAshes(){const g=group('ashes');const p=particles(4200,0x9a8f84,.045,[34,25,30],g);p.userData.flow='ash';const sun=new T.Mesh(new T.SphereGeometry(1.1,32,24),new T.MeshBasicMaterial({color:0xf0c68e}));sun.position.set(5,1,-14);g.add(sun);const halo=new T.Mesh(new T.TorusGeometry(5,.018,5,180),new T.MeshBasicMaterial({color:0xbaa47f,transparent:true,opacity:.3}));halo.position.copy(sun.position);halo.userData.spin=.04;g.add(halo)}
buildOrigin();buildCity('megacity');buildCity('frozen',true);buildEcho();buildLibrary();buildTrain();buildAshes();
const presets={origin:[[0,5,24],[3,0,-8],0x030909,.014],megacity:[[13,8,24],[0,2,-22],0x07090c,.012],frozen:[[-12,5,23],[3,0,-25],0x07131b,.021],echo:[[0,2,21],[0,0,-13],0x031110,.024],library:[[0,4,23],[0,2,-18],0x130d08,.016],train:[[0,1,18],[0,-1,-25],0xb8c1c8,.009],ashes:[[0,2,21],[5,1,-14],0x000000,.028]};
function setWorld(name){Object.values(worlds).forEach(g=>g.visible=g.name===name);const p=presets[name];targetCam.fromArray(p[0]);targetLook.fromArray(p[1]);scene.fog.color.setHex(p[2]);scene.background.setHex(p[2]);scene.fog.density=p[3];els.atmos.textContent=name==='frozen'?'−103.7°C':name==='ashes'?'NULL':name==='train'?'624 KM/S':'STABLE'}
function renderCopy(c){els.no.textContent=c.no;els.en.textContent=c.en;els.loc.textContent=c.loc;els.kicker.textContent=c.kicker;els.title.textContent=c.title;els.sub.textContent=c.sub;els.quote.innerHTML=c.quote;els.body.textContent=c.body;els.action.classList.toggle('hidden',!c.action);els.action.querySelector('span').textContent=c.action;[...els.rail.children].forEach((x,i)=>x.classList.toggle('active',i===current))}
function go(i,instant=false){if(busy&&!instant)return;i=(i+chapters.length)%chapters.length;busy=true;els.copy.classList.add('out');if(!instant){els.trans.classList.remove('play');void els.trans.offsetWidth;els.trans.classList.add('play')}setTimeout(()=>{current=i;const c=chapters[i];setWorld(c.scene);renderCopy(c);els.copy.classList.remove('out')},instant?0:510);setTimeout(()=>busy=false,instant?0:1120)}
chapters.forEach((c,i)=>{const b=document.createElement('button');b.innerHTML=`<span>${c.no}</span>`;b.ariaLabel=`前往${c.title}`;b.onclick=()=>go(i);els.rail.append(b)});
$('#prev').onclick=()=>go(current-1);$('#next').onclick=()=>go(current+1);$('#brand').onclick=()=>go(0);addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowDown')go(current+1);if(e.key==='ArrowLeft'||e.key==='ArrowUp')go(current-1)});addEventListener('wheel',e=>{if(Math.abs(e.deltaY)>35)go(current+(e.deltaY>0?1:-1))},{passive:true});
els.action.onclick=()=>{eventTime=clock.elapsedTime;const c=chapters[current];if(c.scene==='megacity'){els.flash.classList.remove('fire');void els.flash.offsetWidth;els.flash.classList.add('fire');document.body.classList.add('shake');setTimeout(()=>document.body.classList.remove('shake'),500)}else if(c.scene==='ashes')go(0);else{renderer.toneMappingExposure=1.5;setTimeout(()=>renderer.toneMappingExposure=.88,700)}};
let audio=false,audioCtx=null;function tone(){if(!audio)return;if(!audioCtx)audioCtx=new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=55+current*13;o.type='sine';g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.035,audioCtx.currentTime+.08);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+1.4);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+1.5)}$('#sound').onclick=e=>{audio=!audio;e.currentTarget.classList.toggle('off',!audio);tone()};
els.enter.onclick=()=>{started=true;els.boot.classList.add('gone');els.exp.classList.add('ready');tone();go(0,true)};
addEventListener('pointermove',e=>pointer.set(e.clientX/innerWidth*2-1,-(e.clientY/innerHeight*2-1)),{passive:true});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7))});
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),t=clock.elapsedTime;if(started){const px=pointer.x*(current===1||current===2?1.8:.55),py=pointer.y*.45;camera.position.lerp(targetCam.clone().add(new T.Vector3(px,py,0)),reduce?1:.026);look.lerp(targetLook,.035);camera.lookAt(look);const g=worlds[chapters[current].scene];if(g)g.traverse(o=>{if(o.userData.spin){o.rotation.y+=dt*o.userData.spin;o.rotation.x+=dt*o.userData.spin*.35}if(o.userData.float!==undefined)o.position.y+=Math.sin(t*.7+o.userData.float)*dt*.12;if(o.userData.train!==undefined){o.position.x-=dt*(2+o.userData.train*3);if(o.position.x<-52)o.position.x+=104}if(o.userData.flow){o.rotation.y+=dt*(o.userData.flow==='ash'?.08:.01);const a=o.geometry.attributes.position;if(o.userData.flow==='snow'||o.userData.flow==='rain'){for(let i=0;i<a.count;i++){let y=a.getY(i)-dt*(o.userData.flow==='snow'?1.6:3);if(y<-17)y=17;a.setY(i,y)}a.needsUpdate=true}else if(o.userData.flow==='streak'){o.position.z+=dt*13;if(o.position.z>20)o.position.z=-20}else if(o.userData.flow==='dust')o.rotation.z+=dt*.015}});if(current===1&&t-eventTime<3.4){const age=t-eventTime;camera.position.x+=Math.sin(t*70)*Math.max(0,1-age/3)*.12;worlds.megacity.rotation.z=Math.sin(t*40)*Math.max(0,1-age/3)*.006}els.coord.textContent=`X ${camera.position.x.toFixed(1)} / Z ${camera.position.z.toFixed(1)}`;const d=new Date();els.clock.textContent=d.toISOString().slice(11,19)}renderer.render(scene,camera)}animate();setWorld('origin');renderCopy(chapters[0]);
})();
